//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSTN_Facebook_Tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user {
            get {
                return ((string)(this["user"]));
            }
            set {
                this["user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pass {
            get {
                return ((string)(this["pass"]));
            }
            set {
                this["pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string license_id {
            get {
                return ((string)(this["license_id"]));
            }
            set {
                this["license_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string license_key {
            get {
                return ((string)(this["license_key"]));
            }
            set {
                this["license_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool group_reload {
            get {
                return ((bool)(this["group_reload"]));
            }
            set {
                this["group_reload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"ad post bài hay quá :D,cho mình xin 1 slot với,mình có thể đặt hàng bằng cách nào?,ad cho mình hỏi có ship hàng về Thái Nguyên không vậy?,ad ơi PM mình hỏi tí,cái này hay quá :x,cái này còn hàng không bạn?,chờ mãi zz,sp này dùng được cho những đối tượng nào hả ad?,bên mình ship hàng HN free hả?,cái này rẻ thế o.0,mình ở Nhổn muốn ship hàng trong ngày hôm nay được không?,Anh ơi em ở miền Nam chuyển khoản vào đc không ah,Hang moi ha a,cai nay con hang khong anh?,@Đào Anh mày xem đi,@Tún xem này,#Nguyen Lan có phải cái m bảo k?,Con hang k ad,có hỗ trợ mua bằng thẻ visa không bạn,Bạn có ship hàng ra Đà Nẵng không?,^^,bá đạo,quá ngon,giá đẹp,bạn ơi bạn tư vấn thêm cho mình được không?,ad oi cai nay gia nhiu,về gom thóc thôi :)),#Phạm Thanh hàng xịn này,rực rỡ quá o.0,iều này cũng không làm todayTV thôi phát sóng cô dâu 8 tuổi đâu :)),#Thành Vũ hốt luôn đi m,có tiền là hốt ngay :x,giá này là tổng hả ad?")]
        public string comments {
            get {
                return ((string)(this["comments"]));
            }
            set {
                this["comments"] = value;
            }
        }
    }
}
